### ISSUE TITLE
Adding NXDK to Visual Studio?

### ISSUE THREAD

**Issue by chrisderwahre** [xqemu/nxdk#33]
Hey there! I want to test out some Homebrew Developing with NXDK, so how can i add it to Visual Studio? A fast answer would be great!

**Comment by JayFoxRox** [comment]
Not sure what you are asking here.

You won't be debugging with VS anyway. So at best you can run the makefile, you can do this by adding a custom cmake build step, or possibly even using some VS feature.

If you wanted to be real fancy you could write a CMake toolchain file for nxdk, but it involves a ton of modifications due to the bad design of nxdk. I once worked on this, and there might be a branch on my repo, not sure if I ever uploaded it though.

If I was you I'd just write code in VS if that is your prefered editor, but then run make in a terminal like real men do.

**Comment by chrisderwahre** [comment]
Hey, thanks for the answer! i was asking how can i use nxdk in visual studio (im new to c/c++ coding and dont know how to use some libaries like this).

**Comment by JayFoxRox** [comment]
Your question still doesn't make sense to me. This is not a lib, it's (more or less) a toolchain (with build system, some libs) which requires you to use lld as linker.
You can use VS as an editor just fine. Except for that there is no integration for VS at all. So if you want it, you have to somehow hook the `make` into VS - but that's not specific to NXDK, so you are asking in the wrong location.

---

I'd advise you to ditch VS for NXDK and just run it through the Linux subsystem https://github.com/xqemu/nxdk/wiki/Installing-the-nxdk .

Alternatively msys should work.

**Comment by chrisderwahre** [comment]
Ok thanks, :)
